/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          page:     'var(--bg-page)',
          base:     'var(--bg-base)',
          raised:   'var(--bg-raised)',
          elevated: 'var(--bg-elevated)',
          overlay:  'var(--bg-overlay)',
        },
        text: {
          primary:   'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary:  'var(--text-tertiary)',
          muted:     'var(--text-muted)',
        },
        forest: {
          50:  '#F0F6F4',
          100: '#E8F2EF',
          200: '#C3DDD7',
          300: '#7DB8AC',
          400: '#4A8C78',
          500: '#2D6A5A',
          600: '#1C4A3E',
          700: '#123329',
          900: '#0A1F18',
        },
        clay: {
          50:  '#FBF3EF',
          100: '#F5EAE4',
          200: '#E8C9BA',
          300: '#C8815F',
          400: '#A85A3A',
          500: '#8C4A2F',
          600: '#6B2810',
          800: '#4A1A08',
        },
        sage: {
          50:  '#F2F6EE',
          100: '#EBF2E6',
          200: '#CDDFC3',
          300: '#8DB37A',
          400: '#6A9455',
          500: '#5A7A4A',
          600: '#3A5A2A',
          800: '#243818',
        },
        stone: {
          0:   '#FFFFFF',
          50:  '#F7F5F0',
          100: '#EAE7DF',
          200: '#D4D0C5',
          300: '#B8B4A6',
          400: '#9C9888',
          500: '#7A7668',
          600: '#5C5A50',
          700: '#4A4840',
          800: '#3A3830',
          900: '#1E1D18',
        },
        success:  'var(--color-success)',
        warning:  'var(--color-warning)',
        error:    'var(--color-error)',
        danger:   'var(--color-danger)',
        border: {
          subtle:  'var(--border-subtle)',
          DEFAULT: 'var(--border-default)',
          strong:  'var(--border-strong)',
        },
      },
      fontFamily: {
        heading: ['var(--font-heading)', 'Georgia', 'serif'],
        body:    ['var(--font-body)', 'system-ui', 'sans-serif'],
        mono:    ['var(--font-mono)', 'monospace'],
      },
      borderRadius: {
        xs:   'var(--radius-xs)',
        sm:   'var(--radius-sm)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        '2xl':'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs:       'var(--shadow-xs)',
        sm:       'var(--shadow-sm)',
        md:       'var(--shadow-md)',
        lg:       'var(--shadow-lg)',
        xl:       'var(--shadow-xl)',
        forest:   'var(--shadow-forest)',
        clay:     'var(--shadow-clay)',
        sage:     'var(--shadow-sage)',
        'forest-ring': '0 0 0 3px rgba(45, 106, 90, 0.12)',
      },
      animation: {
        'fade-up':      'fade-up 0.4s ease both',
        'fade-in':      'fade-in 0.3s ease both',
        'bubble-left':  'bubble-in-left  0.3s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'bubble-right': 'bubble-in-right 0.2s ease-out both',
        'mic-pulse':    'mic-pulse 2.2s ease infinite',
        'cursor-blink': 'cursor-blink 0.8s step-end infinite',
        'pulse-dot':    'pulse-dot 2s ease infinite',
        'waveform':     'waveform-anim 0.9s ease infinite',
        'voice-wave':   'voice-wave 1s ease-in-out infinite',
      },
      keyframes: {
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(14px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        'bubble-in-left': {
          from: { opacity: '0', transform: 'translateX(-12px) scale(0.94)' },
          to:   { opacity: '1', transform: 'translateX(0) scale(1)' },
        },
        'bubble-in-right': {
          from: { opacity: '0', transform: 'translateX(12px) scale(0.94)' },
          to:   { opacity: '1', transform: 'translateX(0) scale(1)' },
        },
        'mic-pulse': {
          '0%':   { boxShadow: '0 0 0 0 rgba(90, 122, 74, 0.4)' },
          '70%':  { boxShadow: '0 0 0 22px rgba(90, 122, 74, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(90, 122, 74, 0)' },
        },
        'cursor-blink': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%':      { opacity: '0.4', transform: 'scale(0.75)' },
        },
        'waveform-anim': {
          '0%, 100%': { height: '5px',  opacity: '0.35' },
          '50%':      { height: '20px', opacity: '1' },
        },
        'voice-wave': {
          '0%, 100%': { height: '5px',  opacity: '0.35' },
          '50%':      { height: '20px', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
