"""Pydantic schemas for Agentic Forms v1 endpoints."""

from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


class LoginRequest(BaseModel):
    email: str
    password: str


class MeResponse(BaseModel):
    id: str
    email: str
    full_name: str
    memberships: list[dict[str, str]]


# ---------------------------------------------------------------------------
# Form field schema (agentic form definition)
# ---------------------------------------------------------------------------

class FormField(BaseModel):
    """A single field the agent should collect."""

    name: str
    type: Literal["text", "email", "number", "phone", "url", "date", "select", "boolean"] = "text"
    required: bool = True
    description: str = ""


# ---------------------------------------------------------------------------
# Form generation (AI-powered)
# ---------------------------------------------------------------------------

class FormGenerateRequest(BaseModel):
    """Admin's natural language prompt describing what to collect."""

    prompt: str = Field(..., min_length=10, description="Natural language description of the form requirements")


class FormGenerateResponse(BaseModel):
    """Structured form definition generated by the LLM."""

    title: str
    description: str
    system_prompt: str
    fields: list[FormField]


# ---------------------------------------------------------------------------
# Form CRUD
# ---------------------------------------------------------------------------

class FormCreateRequest(BaseModel):
    """Create a new agentic form."""

    title: str
    description: str = ""
    slug: str
    mode: Literal["chat", "voice", "chat_voice"] = "chat_voice"
    persona: str = "Friendly and professional"
    system_prompt: str = ""
    fields: list[FormField] = Field(default_factory=list)


class FormCreateResponse(BaseModel):
    id: str
    org_id: str
    slug: str
    status: str


class PublishResponse(BaseModel):
    form_id: str
    status: str


class FormSummary(BaseModel):
    id: str
    org_id: str
    title: str
    description: str
    slug: str
    mode: str
    persona: str
    status: str
    system_prompt: str = ""
    fields_schema: list[dict[str, Any]] = []
    published_version_id: str | None = None
    created_at: str
    updated_at: str


class FormsListResponse(BaseModel):
    forms: list[FormSummary]


class FormDetailResponse(FormSummary):
    """Full form detail including fields schema."""
    pass


class FormUpdateRequest(BaseModel):
    title: str | None = None
    description: str | None = None
    persona: str | None = None
    mode: Literal["chat", "voice", "chat_voice"] | None = None
    system_prompt: str | None = None
    fields: list[FormField] | None = None


# ---------------------------------------------------------------------------
# Public consumer endpoints
# ---------------------------------------------------------------------------

class PublicSessionCreateRequest(BaseModel):
    channel: Literal["chat", "voice"] = "chat"
    locale: str = "en"
    metadata: dict[str, Any] = Field(default_factory=dict)


class PublicSessionCreateResponse(BaseModel):
    session_id: str
    session_token: str
    state: str
    assistant_message: str


class PublicMessageRequest(BaseModel):
    message: str


class PublicMessageResponse(BaseModel):
    session_id: str
    state: str
    accepted: bool
    assistant_message: str


class CompleteSessionResponse(BaseModel):
    session_id: str
    status: str
    submission_id: str | None = None


# ---------------------------------------------------------------------------
# Submissions & exports
# ---------------------------------------------------------------------------

class SubmissionRow(BaseModel):
    submission_id: str
    session_id: str
    completed_at: str
    answers: dict[str, str]


class SubmissionsResponse(BaseModel):
    form_id: str
    total: int
    rows: list[SubmissionRow]


class ExportCreateResponse(BaseModel):
    export_id: str
    status: str
    row_count: int
    file_path: str | None


# ---------------------------------------------------------------------------
# Messages
# ---------------------------------------------------------------------------

class MessageItem(BaseModel):
    id: str
    role: str
    content: str
    created_at: str


class MessagesListResponse(BaseModel):
    session_id: str
    messages: list[MessageItem]


# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------

class TokenRefreshResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


# ---------------------------------------------------------------------------
# Legacy schemas (kept for backward compatibility)
# ---------------------------------------------------------------------------

class GraphNodeIn(BaseModel):
    key: str
    prompt: str
    node_type: Literal["question", "statement"] = "question"
    required: bool = True
    validation: dict[str, Any] = Field(default_factory=dict)


class GraphEdgeIn(BaseModel):
    from_key: str
    to_key: str | None = None
    condition: dict[str, Any] | None = None
