"""Pydantic schemas for Agentic Forms v1 endpoints."""

from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


class LoginRequest(BaseModel):
    email: str
    password: str


class RegisterRequest(BaseModel):
    email: str = Field(..., min_length=5)
    password: str = Field(..., min_length=6)
    full_name: str = Field(default="User")
    org_name: str = Field(default="My Workspace")


class ForgotPasswordRequest(BaseModel):
    email: str


class ResetPasswordRequest(BaseModel):
    token: str
    new_password: str = Field(..., min_length=6)


class MeResponse(BaseModel):
    id: str
    email: str
    full_name: str
    memberships: list[dict[str, str]]
    plan: str = "free"


# ---------------------------------------------------------------------------
# Form field schema (agentic form definition)
# ---------------------------------------------------------------------------

class FormField(BaseModel):
    """A single field the agent should collect."""

    name: str
    type: Literal["text", "email", "number", "phone", "url", "date", "select", "boolean"] = "text"
    required: bool = True
    description: str = ""


# ---------------------------------------------------------------------------
# Form generation (AI-powered)
# ---------------------------------------------------------------------------

class FormGenerateRequest(BaseModel):
    """Admin's natural language prompt describing what to collect."""

    prompt: str = Field(..., min_length=10, description="Natural language description of the form requirements")


class FormGenerateResponse(BaseModel):
    """Structured form definition generated by the LLM."""

    title: str
    description: str
    system_prompt: str
    fields: list[FormField]


# ---------------------------------------------------------------------------
# Form CRUD
# ---------------------------------------------------------------------------

class FormBranding(BaseModel):
    logo_url: str = ""
    primary_color: str = "#2d6a5a"
    accent_color: str = "#c17c5a"
    font: str = "Inter"
    background_color: str = "#f7f5f0"


class FormCreateRequest(BaseModel):
    """Create a new agentic form."""

    title: str
    description: str = ""
    slug: str
    mode: Literal["chat", "voice", "chat_voice"] = "chat_voice"
    persona: str = "Friendly and professional"
    system_prompt: str = ""
    fields: list[FormField] = Field(default_factory=list)
    branding: FormBranding | None = None
    locale: str = "en"
    welcome_message: str = ""
    completion_message: str = "Thank you for your response!"


class FormCreateResponse(BaseModel):
    id: str
    org_id: str
    slug: str
    status: str


class PublishResponse(BaseModel):
    form_id: str
    status: str


class FormSummary(BaseModel):
    id: str
    org_id: str
    title: str
    description: str
    slug: str
    mode: str
    persona: str
    status: str
    system_prompt: str = ""
    fields_schema: list[dict[str, Any]] = []
    published_version_id: str | None = None
    branding: dict[str, Any] = {}
    locale: str = "en"
    welcome_message: str = ""
    completion_message: str = "Thank you for your response!"
    created_at: str
    updated_at: str


class FormsListResponse(BaseModel):
    forms: list[FormSummary]


class DashboardDailyPoint(BaseModel):
    date: str
    count: int


class DashboardFormAggregate(BaseModel):
    form_id: str
    title: str
    slug: str
    status: str
    mode: str
    submission_count: int


class DashboardRecentSubmission(BaseModel):
    submission_id: str
    form_id: str
    form_title: str
    completed_at: str


class OrgDashboardResponse(BaseModel):
    """Org-wide response analytics for the admin workspace."""

    total_submissions: int
    total_sessions: int
    completion_rate_pct: float
    published_forms: int
    draft_forms: int
    submissions_last_7d: int
    submissions_prev_7d: int
    submissions_trend_pct: float | None
    completion_rate_trend_pct: float | None
    avg_completion_seconds: float | None
    submissions_by_channel: dict[str, int]
    daily_submissions: list[DashboardDailyPoint]
    forms: list[DashboardFormAggregate]
    recent_submissions: list[DashboardRecentSubmission]


class FormDetailResponse(FormSummary):
    """Full form detail including fields schema."""
    pass


class FormUpdateRequest(BaseModel):
    title: str | None = None
    description: str | None = None
    slug: str | None = None
    persona: str | None = None
    mode: Literal["chat", "voice", "chat_voice"] | None = None
    system_prompt: str | None = None
    fields: list[FormField] | None = None
    branding: FormBranding | None = None
    locale: str | None = None
    welcome_message: str | None = None
    completion_message: str | None = None


# ---------------------------------------------------------------------------
# Public consumer endpoints
# ---------------------------------------------------------------------------

class PublicSessionCreateRequest(BaseModel):
    channel: Literal["chat", "voice"] = "chat"
    locale: str = "en"
    metadata: dict[str, Any] = Field(default_factory=dict)


class PublicSessionCreateResponse(BaseModel):
    session_id: str
    session_token: str
    state: str
    assistant_message: str


class PublicMessageRequest(BaseModel):
    message: str


class PublicMessageResponse(BaseModel):
    session_id: str
    state: str
    accepted: bool
    assistant_message: str


class CompleteSessionResponse(BaseModel):
    session_id: str
    status: str
    submission_id: str | None = None


# ---------------------------------------------------------------------------
# Submissions & exports
# ---------------------------------------------------------------------------

class SubmissionRow(BaseModel):
    submission_id: str
    session_id: str
    completed_at: str
    answers: dict[str, str]


class SubmissionsResponse(BaseModel):
    form_id: str
    total: int
    rows: list[SubmissionRow]


class ExportCreateResponse(BaseModel):
    export_id: str
    status: str
    row_count: int
    file_path: str | None


# ---------------------------------------------------------------------------
# Messages
# ---------------------------------------------------------------------------

class MessageItem(BaseModel):
    id: str
    role: str
    content: str
    created_at: str


class MessagesListResponse(BaseModel):
    session_id: str
    messages: list[MessageItem]


# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------

class TokenRefreshResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


# ---------------------------------------------------------------------------
# Legacy schemas (kept for backward compatibility)
# ---------------------------------------------------------------------------

class GraphNodeIn(BaseModel):
    key: str
    prompt: str
    node_type: Literal["question", "statement"] = "question"
    required: bool = True
    validation: dict[str, Any] = Field(default_factory=dict)


class GraphEdgeIn(BaseModel):
    from_key: str
    to_key: str | None = None
    condition: dict[str, Any] | None = None


# ---------------------------------------------------------------------------
# Team / Invitations
# ---------------------------------------------------------------------------

class InviteRequest(BaseModel):
    email: str
    role: Literal["org_admin", "org_editor", "org_viewer"] = "org_editor"


class InvitationResponse(BaseModel):
    id: str
    email: str
    role: str
    status: str


class AcceptInviteRequest(BaseModel):
    token: str
    password: str = Field(default="", description="Required if user doesn't exist yet")
    full_name: str = "User"


# ---------------------------------------------------------------------------
# Billing
# ---------------------------------------------------------------------------

class PlanInfo(BaseModel):
    plan: str
    responses_limit: int
    forms_limit: int
    voice_minutes_limit: int
    seats_limit: int


class UsageSummary(BaseModel):
    responses_used: int
    responses_limit: int
    voice_minutes_used: float
    voice_minutes_limit: int
    forms_used: int
    forms_limit: int
    seats_used: int
    seats_limit: int
    plan: str


class BillingResponse(BaseModel):
    plan: PlanInfo
    usage: UsageSummary
    stripe_customer_id: str | None = None


class CheckoutSessionResponse(BaseModel):
    checkout_url: str


# ---------------------------------------------------------------------------
# Webhooks
# ---------------------------------------------------------------------------

class WebhookCreateRequest(BaseModel):
    url: str
    events: list[str] = Field(default_factory=lambda: ["submission.created"])


class WebhookResponse(BaseModel):
    id: str
    url: str
    events: list[str]
    is_active: bool
    created_at: str


class WebhookDeliveryResponse(BaseModel):
    id: str
    event: str
    status: str
    status_code: int | None
    attempts: int
    created_at: str


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

class FormTemplateResponse(BaseModel):
    id: str
    title: str
    description: str
    category: str
    fields: list[FormField]
    system_prompt: str
    persona: str
    mode: str


# ---------------------------------------------------------------------------
# Analytics (advanced)
# ---------------------------------------------------------------------------

class DropoffStep(BaseModel):
    field_key: str
    field_name: str
    sessions_reached: int
    sessions_answered: int
    dropoff_pct: float


class DropoffFunnelResponse(BaseModel):
    form_id: str
    total_sessions: int
    steps: list[DropoffStep]


class FormAnalyticsResponse(BaseModel):
    form_id: str
    total_sessions: int
    total_submissions: int
    completion_rate_pct: float
    avg_completion_seconds: float | None
    channel_breakdown: dict[str, int]
    dropoff_funnel: list[DropoffStep]
    sentiment_score: float | None


# ---------------------------------------------------------------------------
# API Keys
# ---------------------------------------------------------------------------

class ApiKeyCreateRequest(BaseModel):
    name: str


class ApiKeyCreateResponse(BaseModel):
    id: str
    name: str
    prefix: str
    key: str  # Only returned on creation


class ApiKeyResponse(BaseModel):
    id: str
    name: str
    prefix: str
    is_active: bool
    last_used_at: str | None
    created_at: str
